# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RiverBankErosionAccretion_V2
                                 A QGIS plugin
 RiverBank Erosion and Accretion Analyzer v2 is an advanced QGIS plugin designed to quantify riverbank dynamics by analyzing spatial data over multiple time periods. It provides automated workflows for calculating, visualizing, and reporting erosion and accretion zones along a river’s course.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-24
        copyright            : (C) 2025 by Srija Roy
        email                : roysrija7@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# -*- coding: utf-8 -*-
"""
Initializes the plugin for QGIS.
"""

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RiverBankErosionAccretion_V2 class from file RiverBankErosionAccretion_V2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .RiverBankErosionAccretion_V2 import RiverBankErosionAccretion_V2
    return RiverBankErosionAccretion_V2(iface)
